### ISSUE TITLE
User name is treated as SID by default

### ISSUE THREAD

**Issue by ceremcem** [trac-hacks/authopenid-plugin#22]
I installed this plugin and enabled it in trac.ini file. The "Name" field of OpenID account (which could be set to anything) is used as SID by default. 

I managed to login my trac installation as admin with a trivial OpenID account by setting "User Name" field as "admin" in the OpenID options in my OpenID provider's page. 

I am not able to use my unique OpenID address as SID. 

Platform: Debian Jessie

**Comment by sleske** [comment]
That's weird. Which version of the plugin are you using?

The plugin should not let you log into an existing account, unless the account has the OpenID identifier you used. As of V4.7, the process is:
* Try to look up an existing account by OpenID identifier.
* If found, log user in under the SID stored for the OpenID identifier.
* Otherwise, generate a new SID.
* If the generated SID already exists, appended a number to avoid the collision (unless config option trust_authname is "true", which is not the default).
* Create new account with this SID and OpenID.

So if you use an OpenID account with name field set to "admin", the plugin should try to create a new SID for you, detect that "admin" already exists, and log you in as "admin2".

Could you provide a testcase to reproduce the problem?

**Comment by sleske** [comment]
You write that you are on Debian Jessie, and your report is from June 4, 2014. The current version of the authopenid plugin (V0.4.7) only entered Debian on  Jun 19, 2014 - so you probably used V0.4.1. The problem you describe is likely a duplicate of issue #14 , which was fixed in V0.4.7.

Please re-test your problem with authopenid plugin 0.4.7.

**Comment by ceremcem** [comment]
Thank you for your reply. Since I need a support for authenticating by Google accounts, I switched to oauth2 plugin. That's why I do not have a chance to test easily if authopenid 0.4.7 works correctly or not.

**Comment by sleske** [comment]
Thanks for the feedback. Can you still figure out which version of authopenid you used when the bug occured? Was it the standard version from Debian?

**Comment by ceremcem** [comment]
It seems that your current version would still suffer from this issue. As I'm looking at my patch (provided in second post of this thread), authopenid.py's 311'st and 724'th lines still contains this wrong codes.

**Comment by sleske** [comment]
Yes, the lines you patched are unchanged. However, as far as I can see, what solved the problem for you was not the patch but enabling "combined_username". If "combined_username" is enabled, the OpenID identity URL is included in the SID, which avoids collisions like you described.
Your patches only change the UI (first line), and remove the value of the "Name" field from the SID, both of which is not necessary to solve the problem.

Anyway, if you could confirm what version of authopenid you used, that would be helpful. Otherwise, I'll probably have to close this bug, as I cannot reproduce the problem, at least not with the current version.

**Comment by ceremcem** [comment]
I really can't say if the version I used is the latest one or not (probably not). So, since it seems that the solution is enabling `combined_username` option in the `trac.ini` file, I think we should really close the issue.
